name: Auto-add issues to project

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ secrets.GH_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
